In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings # used to ignore mix datatype
warnings.filterwarnings('ignore')

In [24]:
df = pd.read_csv("cars.csv")
df

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,46120
11910,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,56670
11911,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50620
11912,Acura,ZDX,2013,premium unleaded (recommended),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50920
11913,Lincoln,Zephyr,2006,regular unleaded,221.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Sedan,26,17,61,28995

#### Check Duplicate Records

In [25]:
df[df.duplicated]

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
14,BMW,1 Series,2013,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,19,3916,31500
18,Audi,100,1992,regular unleaded,172.0,6.0,MANUAL,front wheel drive,4.0,Luxury,Midsize,Sedan,24,17,3105,2000
20,Audi,100,1992,regular unleaded,172.0,6.0,MANUAL,front wheel drive,4.0,Luxury,Midsize,Sedan,24,17,3105,2000
24,Audi,100,1993,regular unleaded,172.0,6.0,MANUAL,front wheel drive,4.0,Luxury,Midsize,Sedan,24,17,3105,2000
25,Audi,100,1993,regular unleaded,172.0,6.0,MANUAL,front wheel drive,4.0,Luxury,Midsize,Sedan,24,17,3105,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11481,Suzuki,X-90,1998,regular unleaded,95.0,4.0,MANUAL,four wheel drive,2.0,NaN,Compact,2dr SUV,26,22,481,2000
11603,Volvo,XC60,2017,regular unleaded,302.0,4.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Luxury,Performance",Midsize,4dr SUV,29,20,870,46350
11604,Volvo,XC60,2017,regular unleaded,240.0,4.0,AUTOMATIC,front wheel drive,4.0,"Crossover,Luxury",Midsize,4dr SUV,30,23,870,40950
11708,Suzuki,XL7,2008,regular unleaded,252.0,6.0,AUTOMATIC,all wheel drive,4.0,Crossover,Midsize,4dr SUV,22,15,481,29149
11717,Suzuki,XL7,2008,regular unleaded,252.0,6.0,AUTOMATIC,front wheel drive,4.0,Crossover,Midsize,4dr SUV,22,16,481,27499

In [26]:
duplicated_rows = df[df.duplicated]
print("number of duplicated rows: ", duplicated_rows.shape)

number of duplicated rows:  (715, 16)

#### Drop Duplicate Records

In [27]:
df = df.drop_duplicates()
df

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,46120
11910,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,56670
11911,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50620
11912,Acura,ZDX,2013,premium unleaded (recommended),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50920
11913,Lincoln,Zephyr,2006,regular unleaded,221.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Sedan,26,17,61,28995

#### Check missing or null values

In [28]:
print(df.isnull().sum())

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3376
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

#### Drop missing or null values

In [29]:
df.dropna()

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,46120
11910,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,56670
11911,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50620
11912,Acura,ZDX,2013,premium unleaded (recommended),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50920
11913,Lincoln,Zephyr,2006,regular unleaded,221.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Sedan,26,17,61,28995

#### Show top 10 average MSRP (Price) per car brand (rounded figure)?

In [49]:
df.groupby("Make")["MSRP"].mean().sort_values(ascending=False).head(10).round() # sorting values to get top 10

Make
Bugatti         1757224.0
Maybach          546222.0
Rolls-Royce      351131.0
Lamborghini      331567.0
Bentley          247169.0
McLaren          239805.0
Ferrari          238219.0
Spyker           214990.0
Aston Martin     198123.0
Maserati         113684.0
Name: MSRP, dtype: float64

#### Show the average MSRP (price) per years (rounded figure)?

In [41]:
avg_msrp = df.groupby('Year')['MSRP'].mean().round()
avg_msrp

Year
1990     2032.0
1991     2119.0
1992     2108.0
1993     2245.0
1994     2394.0
1995     2700.0
1996     2567.0
1997     3165.0
1998     3036.0
1999     3154.0
2000     3197.0
2001    41501.0
2002    33744.0
2003    39774.0
2004    36107.0
2005    36747.0
2006    32075.0
2007    35278.0
2008    56754.0
2009    50404.0
2010    52021.0
2011    57570.0
2012    61959.0
2013    51476.0
2014    65523.0
2015    47506.0
2016    47864.0
2017    42185.0
Name: MSRP, dtype: float64

#### Show average Engine HP (power) rounded figure and MPG (efficiency) rounded figure per year?

Hint: Average of (city mpg + highway MPG)

In [33]:
df['MPG'] = (df["highway MPG"] + df["city mpg"])/2

avg_hp_mpg = df.groupby("Year")[["Engine HP","MPG"]].mean().round()
avg_hp_mpg

      Engine HP   MPG
Year
1990      144.0  20.0
1991      151.0  20.0
1992      148.0  22.0
1993      155.0  22.0
1994      157.0  21.0
1995      177.0  20.0
1996      174.0  21.0
1997      185.0  19.0
1998      194.0  19.0
1999      191.0  20.0
2000      185.0  21.0
2001      194.0  21.0
2002      196.0  20.0
2003      206.0  20.0
2004      215.0  20.0
2005      219.0  20.0
2006      229.0  20.0
2007      253.0  19.0
2008      261.0  20.0
2009      254.0  21.0
2010      253.0  21.0
2011      263.0  22.0
2012      272.0  22.0
2013      277.0  24.0
2014      298.0  25.0
2015      274.0  25.0
2016      276.0  25.0
2017      275.0  25.0

#### What percentage of cars are Compact, Midsize, or Large?

In [40]:
vehicle_size = (df["Vehicle Size"].value_counts(normalize = True)*100).round(2).reset_index(name= "Percentage (%)")
vehicle_size

  Vehicle Size  Percentage (%)
0      Compact           39.24
1      Midsize           36.80
2        Large           23.96

#### Which vehicle styles are the most sold (most common) in the dataset?

In [45]:
style_count = df["Vehicle Style"].value_counts().reset_index(name= "Counts")
style_count

          Vehicle Style  Counts
0                 Sedan    2843
1               4dr SUV    2434
2                 Coupe    1175
3           Convertible     741
4         4dr Hatchback     663
5       Crew Cab Pickup     655
6   Extended Cab Pickup     597
7                 Wagon     562
8         2dr Hatchback     412
9     Passenger Minivan     389
10   Regular Cab Pickup     345
11        Passenger Van     121
12              2dr SUV      91
13            Cargo Van      84
14        Cargo Minivan      59
15      Convertible SUV      28

#### Which car brands have the most vehicles priced at $40,000 or more and with a popularity score of at least 1000?

In [46]:
cond = (df["MSRP"] >= 40000) & (df["Popularity"] >= 1000)

brands = df[cond]["Make"].value_counts().reset_index(name = "Vehicle Count")
brands

           Make  Vehicle Count
0      Cadillac            354
1           BMW            269
2          Audi            224
3     Chevrolet            216
4          Ford            145
5       Porsche            123
6        Toyota            120
7        Nissan             91
8       Ferrari             69
9         Dodge             55
10  Lamborghini             52
11     Chrysler             18
12        Tesla             18
13          Kia             17
14        Honda             14
15      Hyundai             13